[tool.poetry]
name = "learn_python"
version = "0.1.0"
description = "Изучение Python."
authors = ["vasil4enko-vs <vvs170@gmail.com>"]
license = "CC BY-SA"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
flake8 = "^4.0.1"
black = "^21.12b0"
mypy = "^0.910"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
