[tool.poetry]
name = "learn-python"
version = "0.1.0"
description = "Изучение Python."
authors = ["vasil4enko-vs <vvs170@gmail.com>"]
license = "CC BY-SA 4.0"
packages = [{include = "learn-python"}]

[tool.poetry.dependencies]
python = "^3.10.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
