[tool.poetry]
name = "learn-python"
version = "0.1.0"
description = "Изучение Python."
authors = ["vasil4enko-vs <vvs170@gmail.com>"]
license = "CC BY-SA 4.0"

[tool.poetry.dependencies]
python = "^3.10.4"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
flake8 = "^4.0.1"
black = "^22.3.0"
mypy = "^0.950"
bandit = "^1.7.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
